### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by SimonSarazin**

### CODE REVIEW

**Comment by Karmak23** [comment]
No need for this PR anymore, shouldn't we just squash it ?

**Comment by SimonSarazin** [comment]
As you want, i deleted group and projectteam in thie pullrequest

**Comment by freddylimpens** [comment]
@SimonSarazin yes, but this PR also have migrations that both create and delete a Community class, so we'd rather make another PR with just "group" and "ProjectTeam" deletion.

**Comment by Karmak23** [comment]
agreed with @freddylimpens.
migrations are polluting the database schema with useless ins & outs.

@SimonSarazin if you are familliar with `git rebase -i`, you can just `rm` the migrations files & commit, then rebase all the commits of this PR and make them appear as one patch that do only the group / project-team removal in serializers, squashing intermediate commits.

This could be more complex in practice (from my point of view it's 3 CLI commands) than deleting this PR and doing a new one, but could enhance your practice of `git` advanced usage to make clean patches. We can `skype` it if you need ;-)

regards,

**Comment by SimonSarazin** [comment]
J'ai essayé de faire comme tu m'as dis :-) Cela a pas été simple mais ça devrait fonctionner. En ajoutant aussi les dernières mises à jour de master. Tu me diras si ça te convient

**Comment by SimonSarazin** [comment]
En fait j'annule cette pull request, je ne veux pas la faire sur la 1.4, mais sur la dernière version de master.

**Pull request closed without merging**
